### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by forflo** [alphapapa/bucket#3]
Could you imagine a bucket that manages it's contents
network transparently? The registers would have to be
kept in sync, which would be the most complex part.
A shell script wouldn't be very suited for this purpose. But
I know of [openreplica](http://openreplica.org/) which makes 
distributed synchronization of all kinds of objects
considerably easy in python.

It'd also be very nice to have something
like an in-memory mode where everything would be kept in ram and 
got lost if you'd turn off your computer.

**Comment by alphapapa** [comment]
Hey, thanks for the suggestions.  Those are interesting ideas, but I think they are basically out-of-scope for this project.  This is really just a simple shell script that stores text in files.

For the sync idea, there are several solutions that I can think of that might do what you need.  For example, for bi-directional sync, Unison is a great tool.  It can be run manually or as a cron job.  It won't handle conflicts automatically, but that might not be an issue, depending on your usage patterns.  You could also use one of the inotify-cron-like tools to run Unison as soon as files are changed, rather than on a schedule.

Of course, you could always use a tool like Dropbox.  Just store the buckets in Dropbox, either by symlinking `~/.cache/bucket` or by using `--directory` to set the directory.  And you could also store buckets on a mounted network filesystem, like Samba, NFS, or SSHFS.

For RAM-only usage, you could mount a tmpfs to your bucket directory.  That would probably take care of it easily enough.

However, please keep in mind that this is meant to be a very simple, yet flexible tool.  I certainly don't endorse using it for any sensitive data.  :)  If you have those kinds of needs, you should probably encrypt your disk or homedir, and use encrypted /tmp and swap.

What do you think?  :)

**Comment by alphapapa** [comment]
I'm going to go ahead and close this issue, but if you have any other questions or suggestions, feel free to reply.  :)
